#!/bin/sh

# Source settings from .dmenurc
if ! [ -f "$HOME/.dmenurc" ]; then
	cp /usr/share/dmenu/dmenurc $HOME/.dmenurc
fi
. $HOME/.dmenurc

action=$(printf "lock\nlogout\nsuspend\nreboot\nshutdown" | dmenu $DMENU_OPTIONS)

i3session $action
