#!/bin/sh
#
# simple screenshot-script using scrot for manjaro-i3 by oberon@manjaro.org

#_conf=$HOME/.config/i3-scrot.conf

#if ! [ -f $_conf ]; then
	#echo "scrot_dir=$(xdg-user-dir PICTURES)" > $_conf
#fi

#source $_conf

if ! [ -d $SCROT_DIR ]; then
	mkdir -p $SCROT_DIR
fi

if ! [[ -z "$2" ]]; then
    cmd="scrot -d $2"
else
    cmd='scrot'
fi

case "$1" in
	--desk|-d|$NULL)
		cd $SCROT_DIR
	        $cmd &&
		sleep 1 &&
		notify-send "screenshot has been saved in $SCROT_DIR"
		;;
	--window|-w)
		cd $SCROT_DIR
		$cmd -u &&
		sleep 1 &&
		notify-send "screenshot has been saved in $SCROT_DIR"
		;;
	--select|-s)
		cd $SCROT_DIR
		notify-send 'select an area for the screenshot' &
		scrot -s &&
		sleep 1 && notify-send "screenshot has been saved in $SCROT_DIR"
		;;
	--help|-h)
		echo "
available options:
-d | --desk    full screen
-w | --window  active window
-s | --select  selection
-h | --help    display this information

The -d or -w options can be used with a delay
by adding the number of seconds, like for example:
'i3-scrot -w 5'

Default option is 'full screen'.

The file destination can be set in ${_conf}.
Default is $SCROT_DIR
"
		;;
	*)
		echo "
== ! i3-scrot: missing or wrong argument ! ==

available options:
-d | --desk    full screen
-w | --window  active window
-s | --select  selection
-h | --help    display this information

Default option is 'full screen'.

The file destination can be set in ${_conf}.
Default is $SCROT_DIR
"

        exit 2
esac

exit 0
