#!/bin/sh
# /usr/bin/i3exit

case "$1" in
    lock)
        lock-color
        ;;
    logout)
        i3-msg exit
        ;;
    switch_user)
        dm-tool switch-to-greeter
        ;;
    suspend)
        lock-color && i3suspend
        ;;
    hibernate)
        lock-color && i3hibernate
        ;;
    reboot)
        i3reboot
        ;;
    shutdown)
        i3shutdown
        ;;
    *)
        echo "== ! i3exit: missing or invalid argument ! =="
        echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0
