#!/bin/sh

#B='#00000000'  # blank
#C='#ffffff22'  # clear ish
#D='#b58900ff'  # default
#T='#fcbd00dd'  # text
#W='#880000bb'  # wrong
#V='#fcbd00dd'  # verifying

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#ffffffff'  # default
T='#dac99dff'  # text
W='#880000bb'  # wrong
V='#023982dd'  # verifying
# Approximate timeout rate in milliseconds (checked every 5 seconds).
timeout="10000"

# Take a screenshot:
#scrot /tmp/screen.png

#cp ~/.config/wall.png /tmp/screen.png
# Create a blur on the shot:
#convert /tmp/screen.png -paint 1 -swirl 360 /tmp/screen.png
#convert /tmp/screen.png -brightness-contrast -20,-20 -paint 1 -noise 0x8 -blur 9,9 /tmp/screen.png

killall -q compton

i3lock \
    --layoutcolor=$T \
    --timecolor=$T \
    --datecolor=$T \
    --verifcolor=$T \
    --wrongcolor=$W \
    --keyhlcolor=$V \
    --insidecolor=$B      \
    --ringcolor=$T        \
    --linecolor=$B        \
    --separatorcolor=$D   \
    --insidecolor=$B \
    --insidewrongcolor=$B \
    --insidevercolor=$B   \
    --color=#000000 \
    --clock \
    --radius=150 \
    --ring-width=5 \
    --timestr="%H:%M:%S"  \
    --datestr="%A %e, %b %Y" \
    --veriftext="Verifying..."  \
    --wrongtext="Nope!" \
    --noinputtext="BLANK" \
    --time-font=monoisome  \
    --date-font=ibmplexsans  \
    --timesize=40  \
    --datesize=24  \
    -i ~/.config/lockwall.png

# If still locked after $timeout milliseconds, turn off screen.
while [[ $(pgrep -x i3lock) ]]; do
	[[ $timeout -lt $(xssstate -i) ]] && xset dpms force off
	sleep 1
done

# --blur 7              \
# --keylayout 2         \
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc

compton -b
