#!/bin/sh

#B='#00000000'  # blank
#C='#ffffff22'  # clear ish
#D='#b58900ff'  # default
#T='#fcbd00dd'  # text
#W='#880000bb'  # wrong
#V='#fcbd00dd'  # verifying

B='#00000000'  # blank
C='#ffffff22'  # clear ish
D='#ffffffff'  # default
T='#ffffffff'  # text
W='#880000bb'  # wrong
V='#fcbd00dd'  # verifying
# Approximate timeout rate in milliseconds (checked every 5 seconds).
timeout="10000"

# Take a screenshot:
scrot /tmp/screen.png

# Create a blur on the shot:
#convert /tmp/screen.png -paint 1 -swirl 360 /tmp/screen.png
convert /tmp/screen.png -brightness-contrast -10,-10 -paint 1 -blur 15,15 /tmp/screen.png

killall -q compton

i3lock \
--insidevercolor=$C   \
--ringvercolor=$V     \
\
--insidewrongcolor=$C \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$D        \
--linecolor=$B        \
--separatorcolor=$D   \
\
--verifcolor=$T        \
--wrongcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--layoutcolor=$T      \
--keyhlcolor=$W       \
--bshlcolor=$W        \
\
--screen 1            \
-i /tmp/screen.png  \
--clock               \
--indicator           \
--radius 110 \
--timestr="%H:%M:%S"  \
--datestr="%A, %m %Y" \
--veriftext="Verifying..."  \
--wrongtext="Nope!"\

# If still locked after $timeout milliseconds, turn off screen.
while [[ $(pgrep -x i3lock) ]]; do
	[[ $timeout -lt $(xssstate -i) ]] && xset dpms force off
	sleep 1
done

# --blur 7              \
# --keylayout 2         \
# --textsize=20
# --modsize=10
# --timefont=comic-sans
# --datefont=monofur
# etc

compton -b
