#!/bin/sh

# Terminate already running bar instance
killall -q mako

# Wait until the processes have been shut down
while pgrep -u $UID -x mako >/dev/null; do sleep 1; done

mako --background-color "#1a1a1acc" --border-color "#689d6a" --default-timeout 5000 --ignore-timeout 1 --height 300
