#!/bin/sh
#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -x polybar >/dev/null; do sleep 1; done

# Launch bar1 and bar2
#polybar example &

#for i in $(polybar -m | awk -F: '{print $1}'); do MONITOR=$i polybar top -c ~/.config/polybar/config & done
feh --bg-scale ~/.config/wall.png
polybar top &
sleep 1
for i in $(polybar -m | awk -F: '{print $1}')
do
    echo $i
    if [ $i == 'DP-1-2' ]
    then
        polybar top -c ~/.config/polybar/config_vga
    fi
done

echo "Bars launched..."
