#!/bin/sh
#!/usr/bin/env sh

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

for m in $(polybar --list-monitors | cut -d":" -f1 | sort -r); do
    sed "s/monitor/monitor=$m/g" ~/.config/polybar/config > /tmp/polybar-$m
	MONITOR=$m polybar top -c /tmp/polybar-$m &
    echo $m
done

echo "Bars launched..."
