#!/bin/sh
# A dmenu binary prompt script.
# Gives a dmenu prompt labeled with $1 to perform command $2.
# For example:
# `./prompt "Do you want to shutdown?" "shutdown -h now"`

[ $(echo "No\nYes" | dmenu -i -p "$1" -nb "#bd2c40" -sb "#6b1924" -sf white -nf gray -fn mono) \
== "Yes" ] && $2
