#!/bin/sh

# This script is called by i3 on startup.

# Map the caps lock key to super...
setxkbmap -model pc104 -layout 'us,es,ru' -option 'lv3:ralt_switch,grp:alt_shift_toggle,misc:typo,caps:super,grp_led:scroll'
# If you don't want a us international keyboard, rather whatever keyboard
# you set in your installation, comment out the above line and uncomment
# the one below.
#setxkbmap -option caps:super

# But when it is pressed only once, treat it as escape.
xcape -e 'Super_L=Escape'

# Map the menu button to right super as well.
xmodmap -e 'keycode 135 = Caps_Lock'
#keycode 135 = Super_R NoSymbol Super_R
